# Week 2 練習と総合問題解答

In [ ]:
# 以下のライブラリを使うので、あらかじめ読み込んでおいてください
import numpy as np
import numpy.random as random
import numpy.linalg as LA
import scipy as sp
import pandas as pd
from pandas import Series, DataFrame

# 可視化ライブラリ
import matplotlib.pyplot as plt
import matplotlib as mpl
import seaborn as sns
%matplotlib inline

# 小数第３まで表示
%precision 3

'%.3f'

### 2.1.3 練習問題

**問1** \
(1) 1次元であなたの好きな値を要素にもつ同じ長さの`np.ndarray`を2つ作成し、`type()`関数を用いて`np.ndarray`になっていることを確認してください。\
(2) (1)で作成した2つの1次元配列に対して四則演算を行ってください。

In [ ]:
#(1)
array1 =  np.array([1,2,3,4,5])
array2 =  np.array([6,7,8,9,10])

In [ ]:
type(array1)

numpy.ndarray

In [ ]:
type(array2)

numpy.ndarray

In [ ]:
#(2)
print('加法',array1 + array2)
print('減法',array1 - array2)
print('乗法',array1 * array2)
print('除法',array1 / array2)

加法 [ 7  9 11 13 15]
減法 [-5 -5 -5 -5 -5]
乗法 [ 6 14 24 36 50]
除法 [0.167 0.286 0.375 0.444 0.5  ]


**問２**\
1次元配列を一つ入力とし、出力が入力を規格化した1次元配列となるような関数を作成してください。\
ここで、ベクトルの(L2ノルムによる)規格化とは元々のベクトルとは並行で、全ての要素の2乗和の平方根が1となるようにすることです。\
このとき、Numpyの**ユニバーサルな演算や関数のみ**を用いて実装してください。

In [ ]:
def normalize(a):
    return a/np.sqrt(np.sum(a**2))

In [ ]:
array1

array([1, 2, 3, 4, 5])

In [ ]:
print(normalize(array1))
print(np.sqrt(np.sum(normalize(array1)**2)))

[0.135 0.27  0.405 0.539 0.674]
1.0


### 2.2.4練習問題

**問1** インデキシングの基礎\
あなたが作成した任意の配列に対して、前から一番目と後ろから一番目の値を取得して表示してください。

In [ ]:
a = np.array([1,2,3,4,5])
print("前から一番目の値:",a[0])
print("後ろから一番目の値:",a[-1])

前から一番目の値: 1
後ろから一番目の値: 5


**問2** ブールインデックス参照 \
(1) 整数値を値にもつNumpyの1次元配列を引数として、奇数または4で割って2余るような配列の値を列挙する関数を実装してください。\
(2) 正の整数を引数として、その数より小さい正の平方数の個数をブールインデックス参照を用いて求める関数を実装してください\
     (ヒント:十分な数の正の平方数を小さい順に列挙し，その中で引数より小さいものを数える)。

In [ ]:
# (1)
def make_bool_ids(a):
    idx1 = (a % 2 != 0)
    idx2 = (a % 4 == 2)
    idx = idx1 | idx2
    return idx

In [ ]:
# 入力例
a = np.array([1, 1, 2, 2, 3, 3, 4, 4, 5, 5])
idx = make_bool_ids(a)
print(a[idx])
# 出力例
# np.array([1, 1, 2, 2, 3, 3, 5, 5])

[1 1 2 2 3 3 5 5]


In [ ]:
# (2)
def count_square(n):
    array = np.arange(1,n) ** 2
    answer = np.sum((array < n))
    return answer

In [ ]:
# (2)別解
def count_square(n):
    array = np.arange(1,n)
    answer = np.sum((array < np.sqrt(n)))
    return answer  

In [ ]:
# 入力例
n = 20
answer = count_square(n)
print(answer)
# 出力例
# 20未満の正の平方数は1, 4, 9, 16
# 4

4


### 2.3.4 練習問題

**問1**
(1) 5人の生徒の4回分のテストの点数の結果を100点満点で2次元配列に格納してください。\
このとき、axis 0を生徒でaxis 1をテストの各回だとします。また，値は任意であるとします。

(2) それぞれの生徒の4回分のテスト結果の最高点・最低点・平均・分散をそれぞれ計算してください。\
その結果をaxis 0が生徒、axis 1が集約結果(最高点・最低点・平均・分散)となる2次元配列にしてください。

(3) 各テストの点数について、その点数がその生徒の平均点から絶対値で何点差かを求めた`shape=(5, 4)`の2次元配列を計算してください。

In [ ]:
# (1)
array = np.array([[90, 100, 80,56],
                      [67, 94, 29,90],
                      [94, 56, 92,74],
                      [39, 46, 62,74],
                      [23, 48, 81,83]
                      ])

In [ ]:
# (2)
print('student1',
      f'最高点:{np.max(array, axis=1)[0]}',
      f'最低点:{np.min(array, axis=1)[0]}',
      f'平均点:{np.mean(array, axis=1)[0]}',
      f'分散:{np.var(array, axis=1)[0]}')

print('student2',
      f'最高点:{np.max(array, axis=1)[1]}',
      f'最低点:{np.min(array, axis=1)[1]}',
      f'平均点:{np.mean(array, axis=1)[1]}',
      f'分散:{np.var(array, axis=1)[1]}')

print('studet3',
      f'最高点:{np.max(array, axis=1)[2]}',
      f'最低点:{np.min(array, axis=1)[2]}',
      f'平均点:{np.mean(array, axis=1)[2]}',
      f'分散:{np.var(array, axis=1)[2]}')

print('student4',
      f'最高点:{np.max(array, axis=1)[3]}',
      f'最低点:{np.min(array, axis=1)[3]}',
      f'平均点:{np.mean(array, axis=1)[3]}',
      f'分散:{np.var(array, axis=1)[3]}')

print('student5',
      f'最高点:{np.max(array, axis=1)[4]}',
      f'最低点:{np.min(array, axis=1)[4]}',
      f'平均点:{np.mean(array, axis=1)[4]}',
      f'分散:{np.var(array, axis=1)[4]}')

array2 = np.array(
    [
        [np.max(array, axis=1)[0],np.min(array, axis=1)[0],np.mean(array, axis=1)[0],np.var(array, axis=1)[0]],
        [np.max(array, axis=1)[1],np.min(array, axis=1)[1],np.mean(array, axis=1)[1],np.var(array, axis=1)[1]],
        [np.max(array, axis=1)[2],np.min(array, axis=1)[2],np.mean(array, axis=1)[2],np.var(array, axis=1)[2]],
        [np.max(array, axis=1)[3],np.min(array, axis=1)[3],np.mean(array, axis=1)[3],np.var(array, axis=1)[3]],
        [np.max(array, axis=1)[4],np.min(array, axis=1)[4],np.mean(array, axis=1)[4],np.var(array, axis=1)[4]],
    ]
)

student1 最高点:100 最低点:56 平均点:81.5 分散:266.75
student2 最高点:94 最低点:29 平均点:70.0 分散:666.5
studet3 最高点:94 最低点:56 平均点:79.0 分散:237.0
student4 最高点:74 最低点:39 平均点:55.25 分散:186.6875
student5 最高点:83 最低点:23 平均点:58.75 分散:619.1875


In [ ]:
array2

array([[100.   ,  56.   ,  81.5  , 266.75 ],
       [ 94.   ,  29.   ,  70.   , 666.5  ],
       [ 94.   ,  56.   ,  79.   , 237.   ],
       [ 74.   ,  39.   ,  55.25 , 186.688],
       [ 83.   ,  23.   ,  58.75 , 619.188]])

In [ ]:
array2[:,2].reshape(5,1)

array([[81.5 ],
       [70.  ],
       [79.  ],
       [55.25],
       [58.75]])

In [ ]:
# (3)
array3 = np.abs(array-array2[:,2].reshape(5,1))

In [ ]:
print(array3)
print(array3.shape)

[[ 8.5  18.5   1.5  25.5 ]
 [ 3.   24.   41.   20.  ]
 [15.   23.   13.    5.  ]
 [16.25  9.25  6.75 18.75]
 [35.75 10.75 22.25 24.25]]
(5, 4)


### 2.4.4 練習問題

**問1**\
(1) 0~99までの100個の連続整数を値にもつ1次元の`np.ndarray`を作成し，shapeが`(10, 10)`の2次元配列となるように整形してください。\
(2) (1)の配列から偶数行目を抜き出したshapeが`(5, 10)`の2次元配列を作成してください。ただし行は0から数えます。\
(3) (1)の配列から奇数列目を抜き出したshapeが`(10, 5)`の2次元配列を作成してください。ただし列は0から数えます。\
(4) (1)の配列から，偶数行目かつ奇数列目にある値を要素にもつshapeが`(5, 5)`の2次元配列を作成してください。ただし行と列は0から数えます。

In [ ]:
# (1)
array1 = np.arange(0,100).reshape(10,10)
array1

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [ ]:
# (2)
idx1 = np.arange(0,array1.shape[0],2)
array1[idx1, :]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89]])

In [ ]:
# (3)
idx2 = np.arange(1,array1.shape[0],2)
array1[:,idx2]

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29],
       [31, 33, 35, 37, 39],
       [41, 43, 45, 47, 49],
       [51, 53, 55, 57, 59],
       [61, 63, 65, 67, 69],
       [71, 73, 75, 77, 79],
       [81, 83, 85, 87, 89],
       [91, 93, 95, 97, 99]])

In [ ]:
#(4)
array1[np.ix_(idx1, idx2)]

array([[ 1,  3,  5,  7,  9],
       [21, 23, 25, 27, 29],
       [41, 43, 45, 47, 49],
       [61, 63, 65, 67, 69],
       [81, 83, 85, 87, 89]])

### 2.6.2 練習問題

**問1**\
(1) 1次元配列に対して、最大値のインデックスを取得する関数を自分で調べて，実行してください。\
(2) 2次元配列のaxis 1の方向で各最大値のインデックスを取得してください。\
(3) 2次元配列の最大値のインデックスの場所が何行何列目かを取得する操作を自分で調べて実装してください。

In [ ]:
#(1) 
#入力例
a = np.array([3, 8, 2, 6, 4, 4])
print(np.argmax(a))
# 出力例
# 1

#(2)
# 入力例
a = np.array([3, 8, 2, 6, 4, 4]).reshape(2, 3)
print(a)
print(np.argmax(a))
print(np.argmax(a,axis=1))
# 出力例
# [[1],
#[0]]

#(3)
def toi3(a):
    max_value = np.min(a)
    ret = None
    for row in np.argmax(a, axis=1):
        for col in np.argmax(a, axis=0):
            if a[row,col] > max_value:
                max_value = a[row,col]
                ret = (row, col)
    return ret
    
# 入力例
a = np.array([3, 8, 2, 6, 4, 4]).reshape(2, 3)
print(f'最大値{np.max(a)}は{toi3(a)}成分にある。')
# 最大値8は(0, 1)成分にある
# 出力例
# (0, 1)

1
[[3 8 2]
 [6 4 4]]
1
[1 0]
最大値8は(0, 1)成分にある。


***

## 2.7 総合問題

**問1**\
昨今，深層学習を用いた自然言語処理において，GoogleのTransformerというものをベースとしたモデルがいくつかの自然言語処理タスクで人間越えの精度を出したことで脚光を浴びました。

そして，2020年1月にGoogleはそのTransformerの時間計算量と空間計算量を改善した[Reformer](https://arxiv.org/abs/2001.04451)を発表しました。今回は，この論文の中で，Transformerの時間計算量を改善した部分に用いられた[*cross-polytope LSH*](https://arxiv.org/abs/1509.02897)というものを誘導付きで実装してみましょう。

いま，次の問題を考えます：
>$n$本のベクトルに対して，"似ている"ベクトルには同じ整数値を，"似ていない"ベクトルには異なる整数値を割り当てられる方法を考えたい。このとき，ベクトルが"似ている"とは，ベクトル同士のなす角が0に近いことをいう。

この問題は以下の難点があります：
- なす角がどれくらい以下になれば似ているとして決めるのか。
- ベクトル$a$と$b$, $b$と$c$がそれぞれ"似ている"とき，$a$と$c$が"似ている"とは限らない。
- なす角$\theta$を求めるには内積とノルムを使えば$\cos \theta$を計算できる。この値をソートして整数値をいい感じに割り振れば良さそうだが，基本的にソートは$n$が大きくなると遅い(ベクトルの組合せは$_nC_2$もある)。

そこで次の確率的な解法を考えます:\
①全てのベクトルを同じ角度だけ回転する。このときの回転角はランダムに決める。

②"似ている"ベクトル同士は，回転後も**高確率で**同じ象限にあり，"似ていない"ベクトル同士は**高確率で**違う象限にある。

③よって，ランダムな回転後のそれぞれのベクトルが属する象限の番号をそのベクトルに割り当てる整数値とすれば**高確率で**問題が解ける。

これを実装します。

今回は3次元横ベクトルを100本用意したものを考えます。

In [ ]:
A = random.randn(100, 3) # 3次元横ベクトルを100本縦に積み重ねた行列
print(A)

[[ 3.433e-01  3.931e-01 -6.371e-01]
 [-1.507e+00  6.832e-05  9.954e-01]
 [ 3.632e-01 -1.563e-02 -5.136e-01]
 [ 3.326e-01  2.146e+00  9.277e-01]
 [-1.284e+00  5.662e-01  3.021e-01]
 [-6.306e-01 -1.449e+00  4.134e-01]
 [-1.696e+00  1.296e+00  9.287e-01]
 [ 6.633e-01  3.995e-01  5.211e-01]
 [-4.177e-01 -1.575e+00 -4.437e-01]
 [-1.232e+00 -1.008e+00  9.666e-01]
 [-2.136e-01 -5.649e-01  1.913e+00]
 [-8.751e-01  1.644e+00 -9.428e-01]
 [-4.633e-01  1.282e+00  1.070e+00]
 [-1.051e+00 -8.596e-01  1.189e+00]
 [ 2.217e-01 -6.280e-01  4.320e-01]
 [ 1.527e+00 -4.676e-01 -1.025e+00]
 [ 3.131e-01  2.085e+00 -1.226e+00]
 [ 4.247e-01 -9.250e-01 -1.894e-01]
 [-5.532e-01 -2.594e-01 -6.078e-01]
 [-3.070e-01 -1.035e+00 -1.970e-01]
 [-1.832e+00 -9.192e-02 -3.713e-01]
 [ 1.156e+00  4.442e-01 -2.873e+00]
 [-4.220e-01 -2.868e-01  1.751e+00]
 [ 5.166e-01 -4.354e-02 -6.673e-01]
 [-4.881e-01 -2.634e-02 -1.597e-01]
 [-9.405e-01  2.374e-01  2.076e+00]
 [-1.027e+00 -4.421e-02 -2.546e-02]
 [-9.839e-01  3.501e-02  1.2

(1) 100本のベクトルを回転させる行列Rを生成し，回転後のベクトルを縦に積み重ねた(100, 3)の行列を求めます。ここで，ランダムな回転をする3次元回転行列Rは，`gen_R_3d`関数の引数にランダムに生成された3つの角度パラメータからなる1次元配列を入力することで生成します。

In [ ]:
# (1)
def gen_R_3d(p):
    px, py, pz = p
    Rx = np.array([[1, 0, 0],
                   [0, np.cos(px), np.sin(px)],
                   [0, -np.sin(px), np.cos(px)]])
    Ry = np.array([[np.cos(py), 0, -np.sin(py)],
                   [0, 1, 0],
                   [np.sin(py), 0, np.cos(py)]])
    Rz = np.array([[np.cos(pz), np.sin(pz), 0],
                   [-np.sin(pz), np.cos(pz), 0],
                   [0, 0, 1]])

    return Rz@Ry@Rx

p =  2 * np.pi * random.rand(3)
R = gen_R_3d(p)

B = np.matmul(A, R)
print(B)

[[-0.093  0.102  0.812]
 [-0.977 -0.137 -1.513]
 [ 0.209  0.24   0.543]
 [-1.056 -2.029  0.586]
 [-1.281 -0.047 -0.647]
 [ 0.553  0.776 -1.327]
 [-1.985 -0.759 -0.951]
 [ 0.293 -0.862  0.207]
 [ 0.679  1.385 -0.687]
 [-0.108  0.356 -1.825]
 [ 0.473 -0.975 -1.688]
 [-1.861  0.076  0.943]
 [-1.049 -1.329 -0.368]
 [-0.044  0.04  -1.804]
 [ 0.638 -0.038 -0.471]
 [ 1.297  0.419  1.32 ]
 [-1.317 -0.432  2.007]
 [ 0.901  0.503 -0.079]
 [-0.316  0.802 -0.02 ]
 [ 0.435  0.855 -0.534]
 [-1.337  1.029 -0.811]
 [ 0.173  1.374  2.805]
 [ 0.113 -0.937 -1.56 ]
 [ 0.32   0.307  0.719]
 [-0.363  0.319 -0.176]
 [-0.573 -1.272 -1.817]
 [-0.73   0.441 -0.575]
 [-0.579 -0.55  -1.385]
 [ 2.176 -0.478  1.061]
 [ 0.386 -0.775  0.634]
 [-2.017  0.227  1.518]
 [-2.696  1.623 -0.374]
 [ 1.092 -1.536  1.199]
 [ 0.464 -0.67  -0.887]
 [ 0.224 -0.544  0.298]
 [ 0.351  0.494 -0.242]
 [-0.414 -0.464 -0.756]
 [-1.256  0.387 -1.819]
 [-1.444 -0.416  0.535]
 [ 0.831 -0.281  0.583]
 [-0.841 -1.233  1.249]
 [-0.271  0.147 

(2) (1)で求めたベクトルは大きさも変わってしまっているため規格化する必要があります．(1)の各ベクトルを，(L2)ノルムが1となるように規格化して，順番を変えないまま縦に積み重ねた(100, 3)の行列を求めてください。

In [ ]:
# (2)

B_norm_l2 = LA.norm(B, ord=2, axis=1, keepdims=True)
B_normalized = B / B_norm_l2
print(B_normalized)

[[-0.113  0.124  0.986]
 [-0.541 -0.076 -0.838]
 [ 0.332  0.381  0.863]
 [-0.447 -0.859  0.248]
 [-0.892 -0.033 -0.451]
 [ 0.338  0.475 -0.812]
 [-0.853 -0.326 -0.408]
 [ 0.313 -0.923  0.222]
 [ 0.402  0.82  -0.407]
 [-0.058  0.191 -0.98 ]
 [ 0.236 -0.486 -0.841]
 [-0.891  0.036  0.452]
 [-0.605 -0.767 -0.213]
 [-0.024  0.022 -0.999]
 [ 0.803 -0.047 -0.594]
 [ 0.684  0.221  0.696]
 [-0.54  -0.177  0.823]
 [ 0.87   0.486 -0.077]
 [-0.367  0.93  -0.023]
 [ 0.396  0.779 -0.487]
 [-0.714  0.55  -0.433]
 [ 0.055  0.439  0.897]
 [ 0.062 -0.514 -0.856]
 [ 0.379  0.364  0.851]
 [-0.706  0.62  -0.341]
 [-0.25  -0.555 -0.793]
 [-0.71   0.428 -0.559]
 [-0.362 -0.344 -0.866]
 [ 0.882 -0.194  0.43 ]
 [ 0.359 -0.722  0.591]
 [-0.796  0.09   0.599]
 [-0.851  0.512 -0.118]
 [ 0.489 -0.687  0.537]
 [ 0.385 -0.556 -0.736]
 [ 0.339 -0.825  0.452]
 [ 0.537  0.758 -0.37 ]
 [-0.423 -0.474 -0.772]
 [-0.56   0.172 -0.811]
 [-0.905 -0.261  0.336]
 [ 0.789 -0.267  0.553]
 [-0.432 -0.634  0.642]
 [-0.29   0.157 

(3) (2)で求めたノルム1の100本のベクトルに対して，それらを$-1$倍した100本のベクトルと元の100本のベクトルを，100本の順番を変えないまま**横に**積み重ねた(100, 6)の行列を求めてください。

In [ ]:
# (3)

C = np.concatenate([B_normalized, -B_normalized], axis=1)
print(C)

[[-0.113  0.124  0.986  0.113 -0.124 -0.986]
 [-0.541 -0.076 -0.838  0.541  0.076  0.838]
 [ 0.332  0.381  0.863 -0.332 -0.381 -0.863]
 [-0.447 -0.859  0.248  0.447  0.859 -0.248]
 [-0.892 -0.033 -0.451  0.892  0.033  0.451]
 [ 0.338  0.475 -0.812 -0.338 -0.475  0.812]
 [-0.853 -0.326 -0.408  0.853  0.326  0.408]
 [ 0.313 -0.923  0.222 -0.313  0.923 -0.222]
 [ 0.402  0.82  -0.407 -0.402 -0.82   0.407]
 [-0.058  0.191 -0.98   0.058 -0.191  0.98 ]
 [ 0.236 -0.486 -0.841 -0.236  0.486  0.841]
 [-0.891  0.036  0.452  0.891 -0.036 -0.452]
 [-0.605 -0.767 -0.213  0.605  0.767  0.213]
 [-0.024  0.022 -0.999  0.024 -0.022  0.999]
 [ 0.803 -0.047 -0.594 -0.803  0.047  0.594]
 [ 0.684  0.221  0.696 -0.684 -0.221 -0.696]
 [-0.54  -0.177  0.823  0.54   0.177 -0.823]
 [ 0.87   0.486 -0.077 -0.87  -0.486  0.077]
 [-0.367  0.93  -0.023  0.367 -0.93   0.023]
 [ 0.396  0.779 -0.487 -0.396 -0.779  0.487]
 [-0.714  0.55  -0.433  0.714 -0.55   0.433]
 [ 0.055  0.439  0.897 -0.055 -0.439 -0.897]
 [ 0.062 -

(4)(やや難)いま，3次元空間なので象限は第0〜第7までの8象限あります。ここで，象限を求める代わりに，正規直交基底(標準基底)とその逆向きのベクトル(合わせて6本,適当に番号を振ってよい)のうち最も"似ている"ものの番号を求めるとします。回転後のベクトルの番号を格納した(100, 1)の行列を求めてください。
(ヒント: ベクトルの割り振る番号を求めるのにどうすればいいかを考える。ここで内積を使うと計算が遅い。わからない人は3次元ではなく，2次元のベクトルについて考えてみよう。ここで，(2)で規格化したことを用いるとよいかも)

In [ ]:
# (4)
C_argmax = np.argmax(C, axis=1).reshape(-1,1)
print(C_argmax)

[[2]
 [5]
 [2]
 [4]
 [3]
 [5]
 [3]
 [4]
 [1]
 [5]
 [5]
 [3]
 [4]
 [5]
 [0]
 [2]
 [2]
 [0]
 [1]
 [1]
 [3]
 [2]
 [5]
 [2]
 [3]
 [5]
 [3]
 [5]
 [0]
 [4]
 [3]
 [3]
 [4]
 [5]
 [4]
 [1]
 [5]
 [5]
 [3]
 [0]
 [2]
 [2]
 [4]
 [1]
 [0]
 [3]
 [0]
 [1]
 [5]
 [0]
 [5]
 [3]
 [4]
 [0]
 [4]
 [4]
 [0]
 [2]
 [2]
 [1]
 [2]
 [5]
 [5]
 [0]
 [1]
 [5]
 [3]
 [2]
 [5]
 [0]
 [4]
 [1]
 [1]
 [0]
 [4]
 [4]
 [2]
 [2]
 [2]
 [2]
 [0]
 [4]
 [1]
 [3]
 [4]
 [4]
 [4]
 [3]
 [1]
 [3]
 [3]
 [1]
 [0]
 [2]
 [1]
 [1]
 [2]
 [3]
 [4]
 [4]]


ここで得られた100個の整数が，100本のベクトルに割り当てられる値となる。

(5) (余力のある人)100本のベクトル間の任意の2本のなす角$\theta$の対して$\cos \theta$を計算し，"似ている"ベクトル同士は高確率で同じ整数値が割り振られており，"似ていない"ベクトル同士は高確率で異なる整数値が割り当てられていることを確認してください。

In [ ]:
# (5)

D = B_normalized
D_num = C_argmax

#似ているかどうかを判定するcosの閾値の設定
threshold = 1 / np.sqrt(2)

n_similar = 0           #似ているベクトルの数
n_similar_same = 0      #そのうち番号が同じものの数
n_notsimilar = 0        #似ていないベクトルの数
n_notsimilar_dif = 0    #そのうち番号が異なるものの数
for i in range(100):
    for j in range(i+1,100):
        cos = np.dot(D[i],D[j]) / (LA.norm(D[i]) * LA.norm(D[j]))
        #似ている
        if cos > threshold:
            n_similar += 1
            if D_num[i] == D_num[j]:
                n_similar_same += 1
        #似ていない
        else:
            n_notsimilar += 1
            if D_num[i] != D_num[j]:
                n_notsimilar_dif += 1

print('似ているベクトルのうち、同じ整数値が割り振られている： ',n_similar_same / n_similar)
print('似ていないベクトルのうち、異なる整数値が割り振られている： ',n_notsimilar_dif / n_notsimilar)

似ているベクトルのうち、同じ整数値が割り振られている：  0.6476462196861626
似ていないベクトルのうち、異なる整数値が割り振られている：  0.9204518710284773
